### ISSUE TITLE
Use correct number delimiters

### ISSUE THREAD

**Issue by N-Schaef** [1Hive/uniswap-info#16]
The numbers on info.honeyswap are using the same delimiter symbol "." for decimal places and thousand separator as can be seen in the following picture:
![grafik](https://user-images.githubusercontent.com/7281529/110384243-a5fbf980-805d-11eb-9931-3f9e56cdf312.png)

I think this is pretty confusing and should be replaced. 
As this is a international project, probably to have a space as thousand separator and a comma as decimal separator, as recommended by most institutes responsible for standards.

**Comment by ceresbzns** [comment]
major DeFi protocols like Compound and Sushiswap are all using commas for thousands and periods for decimals
